/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Concurrente;
import Concurrente.Runner;
//import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import Buffer.Buffer;

/**
 *
 * @author Leonardo Gutierrez Velez
 */

public class AthleticRaceInterface extends javax.swing.JFrame {

    /**
     * Creates new form AthleticRaceInterface
     */
    public static int counter =0;
    public static Runner Runners[] = new Runner[5];
    public static Buffer buffer = new Buffer(5);
    
    public AthleticRaceInterface() {
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_RegistrarCorredor = new javax.swing.JLabel();
        jtf_NombreCorredor = new javax.swing.JTextField();
        jb_RegistrarCorredor = new javax.swing.JButton();
        jl_CorredoresRegistrados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_CorredoresRegistrados = new javax.swing.JTextArea();
        jl_Resultados = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_Resultados = new javax.swing.JTextArea();
        jb_Iniciar = new javax.swing.JButton();
        jb_Reiniciar = new javax.swing.JButton();
        jb_Terminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_RegistrarCorredor.setText("Registrar corredor");

        jtf_NombreCorredor.setToolTipText("Ingresar nombre");
        jtf_NombreCorredor.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                CanAddRunner(evt);
            }
        });

        jb_RegistrarCorredor.setText("Registrar");
        jb_RegistrarCorredor.setEnabled(false);
        jb_RegistrarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRunner(evt);
            }
        });

        jl_CorredoresRegistrados.setText("Corredores registrados");

        jta_CorredoresRegistrados.setColumns(1);
        jta_CorredoresRegistrados.setRows(5);
        jScrollPane1.setViewportView(jta_CorredoresRegistrados);

        jl_Resultados.setText("Resultados");

        jta_Resultados.setColumns(20);
        jta_Resultados.setRows(5);
        jScrollPane2.setViewportView(jta_Resultados);
        jta_Resultados.getAccessibleContext().setAccessibleName("");
        jta_Resultados.getAccessibleContext().setAccessibleDescription("");

        jb_Iniciar.setText("Iniciar");
        jb_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarCarrera(evt);
            }
        });

        jb_Reiniciar.setText("Reiniciar");
        jb_Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarCarrera(evt);
            }
        });

        jb_Terminar.setText("Terminar");
        jb_Terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarCarrera(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_RegistrarCorredor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_NombreCorredor)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_CorredoresRegistrados)
                                    .addComponent(jl_Resultados))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jb_RegistrarCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jb_Reiniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jb_Terminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_RegistrarCorredor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_NombreCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_RegistrarCorredor))
                .addGap(12, 12, 12)
                .addComponent(jl_CorredoresRegistrados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_Resultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_Iniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_Reiniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_Terminar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CanAddRunner(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_CanAddRunner
        if(jtf_NombreCorredor.getText().length() ==0 ){ jb_RegistrarCorredor.setEnabled(false);
        }else {jb_RegistrarCorredor.setEnabled(true); }
    }//GEN-LAST:event_CanAddRunner

    private void AddRunner(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRunner
        if(counter <=4 ){
            System.out.println( String.valueOf( counter));
            Runners[counter]=new Runner(jtf_NombreCorredor.getText());
            Runners[counter].theRunner(buffer,jta_Resultados);
            System.out.println("Nuevo corredor: " + Runners[counter].getName() + "Velocidad: "+ Runners[counter].getSpeed() );
            
            JOptionPane.showMessageDialog(null,
                "Nombre: " + Runners[counter].getName()+  "\n Velocidad: "+ Runners[counter].getSpeed()  ,
                "Corredor registrado",
                JOptionPane.INFORMATION_MESSAGE);
            jtf_NombreCorredor.setText("");
            jta_CorredoresRegistrados.append(String.valueOf( counter+1)+ " - " + Runners[counter].getName()+"\n"   );

            counter ++ ;
        }
    }//GEN-LAST:event_AddRunner

    private void iniciarCarrera(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarCarrera
        if(counter==5){
            JOptionPane.showMessageDialog(null
                ,"Iniciando carrera" 
                ,"Carrera"
                ,JOptionPane.INFORMATION_MESSAGE);
            Runners[0].runForestRun();
            Runners[1].runForestRun();
            Runners[2].runForestRun();
            Runners[3].runForestRun();
            Runners[4].runForestRun();
            
        }else JOptionPane.showMessageDialog(null
                ,"No se han registrado los cinco corredores necesarios para iniciar la carrera." 
                ,"Esperando corredores"
                ,JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_iniciarCarrera

    private void reiniciarCarrera(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarCarrera
        counter = 0;
        for (int i = 0; i < 5; i++) {
            Runners[i].setName("");
            jta_CorredoresRegistrados.setText("");
            jta_Resultados.setText("");
        }

    }//GEN-LAST:event_reiniciarCarrera

    private void terminarCarrera(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarCarrera
        JOptionPane.showMessageDialog(null,
  "La applicación se cerrara"  ,
    "Terminar carrera",
    JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_terminarCarrera

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AthleticRaceInterface().setVisible(true);
                
                System.out.println( "Corredores permitidos: "+ Runners.length );
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_Iniciar;
    private javax.swing.JButton jb_RegistrarCorredor;
    private javax.swing.JButton jb_Reiniciar;
    private javax.swing.JButton jb_Terminar;
    private javax.swing.JLabel jl_CorredoresRegistrados;
    private javax.swing.JLabel jl_RegistrarCorredor;
    private javax.swing.JLabel jl_Resultados;
    private javax.swing.JTextArea jta_CorredoresRegistrados;
    private javax.swing.JTextArea jta_Resultados;
    private javax.swing.JTextField jtf_NombreCorredor;
    // End of variables declaration//GEN-END:variables
}
